name: Build and deploy backend - chat-wm-api
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -f backend/chat-backend/pom.xml
      
    - name: Create staging directory and move application jar there
      run: mkdir staging && cp backend/chat-backend/target/*.jar staging
      
    - name: Create web.config for azure
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: "staging/web.config"
        contents: |
          <?xml version='1.0' encoding='UTF-8'?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name='httpPlatformHandler' path='*' verb='*' modules='httpPlatformHandler' resourceType='Unspecified' />
              </handlers>
              <httpPlatform processPath='%JAVA_HOME%\bin\java.exe'
                  arguments='-Djava.net.preferIPv4Stack=true -Dserver.port=%HTTP_PLATFORM_PORT% -jar -Dapplication.properties=application-azure.properties -Djasypt.encryptor.password=${{ secrets.JASYPT_AZURE_PASSWORD }} -Dspring.profiles.active=azure &quot;%HOME%\site\wwwroot\chat-0.0.1.jar&quot;'>
              </httpPlatform>
            </system.webServer>
          </configuration>
      
    - name: Show staging files
      run: "ls staging"
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chat-wm-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cb2046e8a36242c2ab511981ce0c5f58 }}
        package: 'staging'
        
