# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy frontend - chat-wm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, build
      run: |
       cd frontend/client
       npm install
       npm install -g @angular/cli
       ng build --prod
       
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chat-wm'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d10ea7ff6e944ba5b6574dca346644b7 }}
        package: 'frontend/client/dist'
        
